name: CI/CD

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

permissions:
  contents: read
  packages: write

jobs:
  pipeline:
    uses: ArchGenTf/Main/.github/workflows/backend.yml@master
    with:
      service: "api-gateway"
      image: "acrarchgen.azurecr.io/api-gateway"
      trigger: ${{ github.event_name }}
    secrets: inherit
